services:
  kobodl:
    image: ghcr.io/jacobxtyler/kobodl:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kobodl
    restart: unless-stopped
    user: ${PUID:-1000}
    ports:
      - "5000:5000"
    volumes:
      # Map config and download dirs to local $HOME/kobodl/
      - ${HOME}/kobodl/.config:/home/config
      - ${HOME}/kobodl/downloads:/home/downloads
    command: --config /home/config/kobodl.json serve -h 0.0.0.0 -p 5000 --output-dir /home/downloads
